# Generated by Django 5.1.1 on 2024-09-18 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savinggoal',
            old_name='saving_goal_type',
            new_name='goal_type',
        ),
    ]
